# JOBBY website Worker configuration.
name = "jobby"
compatibility_date = "2026-10-01"
workers_dev = true

routes = [
  { pattern = "jobby.lol", custom_domain = true },
  { pattern = "www.jobby.lol", custom_domain = true }
]

[assets]
directory = "./public"
not_found_handling = "single-page-application"

[previews]
